server.port: 8091
spring:
  application:
    name: opex-wallet
  main:
    allow-bean-definition-overriding: false
  kafka:
    bootstrap-servers: ${KAFKA_IP_PORT}
    consumer:
      group-id: wallet
  redis:
    hostname: ${REDIS_HOST}
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT}/opex_wallet
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true

