server.port: 8094
spring:
  application:
    name: opex-api
  main:
    allow-bean-definition-overriding: false
  kafka:
    bootstrap-servers: 192.168.178.29:9092
    consumer:
      group-id: api
  redis:
    host: 127.0.0.1
    port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost/opex_api
    username: opex
    password: hiopex
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
